# Name of the workflow
name: CI Build & Release

# Triggers for running
on:
  workflow_dispatch: # This allows manually running from GitHub web UI
  push:
    branches: ["main"] # Standard CI trigger when main branch is pushed

env:
  IMAGE_NAME: "nanomon"
  IMAGE_REG: "bencacr2025.azurecr.io"
  IMAGE_TAG: ${{ github.sha }}
  VERSION: ${{ github.sha }}
  BUILD_INFO: "CI Build from GitHub Actions"
  ACR_PASSWORD: "${{ secrets.ACR_PASSWORD }}"
  ACR_USERNAME: "bencacr2025"

# One job for building the app
jobs:
  buildJob:
    name: "Build & push images"
    runs-on: ubuntu-latest
    steps:
      # Checkout code from another repo on GitHub
      - name: "Checkout app code repo"
        uses: actions/checkout@v5
        with:
          repository: benc-uk/nanomon

      - name: "Build images"
        run: |
          docker compose -f build/compose.yaml build api frontend runner

      - name: "Login to ACR"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REG }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: "Push images"
        run: |
          docker compose -f build/compose.yaml push api frontend runner
